version: '3'

services:
  streaming-tools:
    build:
      context: .
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: streaming-tools
    env_file:
      - .env
    networks:
      br0:
        ipv4_address: '10.0.4.21'

networks:
  br0:
    external:
      name: br0
